### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by andrewlangston** [ckim310/Welp#2]
Hi Christine,

Great work on your sample state! It's looking good to me. One quick note:

- [x] How are we going to access information about `bookmarks` and `reactions` on the frontend?

Let me know if you have questions!

**Comment by ckim310** [comment]
Hi Andrew,

I've updated my sample state to include the reactionIds nested under the reviews and also the bookmarkIds to be nested in the users.

**Comment by andrewlangston** [comment]
Looks good! Closing this issue.
