### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by andrewlangston** [ckim310/Welp#3]
Hey Christine,

Excellent work on your backend routes. I don't have much in the way of comments. Please see below:

- [x] `GET /api/businesses/:business_id/reviews`. We'll only every view reviews when on a business show page, so we don't need a separate route for fetching reviews. This can be removed.
- [x] Will users have the option of editing their reactions? Or will we handle this by deleting the old one and creating a new one?

Let me know if you have questions!

**Comment by ckim310** [comment]
Hey Andrew,

I'm was thinking that the reactions will just be deleted and new ones will be created rather than updating/editing the reactions.

**Comment by andrewlangston** [comment]
Christine - that sounds good to me. Closing this issue.
